# Generated by Django 4.2.21 on 2025-05-23 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": False},
        ),
    ]
